settings:
  title: 'Status Page IT2G'
  url: 'https://cf-workers-status-page-production.ithard.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mail-it2g # unique identifier
    name: mail.it2g.ru
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://mail.it2g.ru/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: confluence-it2g
    name: confluence.it2g.ru
    description: 'Built for anything connected to the Internet.'
    url: 'https://confluence.it2g.ru'
    method: GET
    expectStatus: 200

  - id: jira-it2g
    name: The Cloudflare Blog
    url: 'https://jira.it2g.ru/'
    method: GET
    expectStatus: 200
